//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLThuVien
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTPM
    {
        public string Maphieu { get; set; }
        public string Manv { get; set; }
        public string Madg { get; set; }
        public string Masach { get; set; }
        public Nullable<System.DateTime> Ngaylapphieu { get; set; }
    
        public virtual Docgia Docgia { get; set; }
        public virtual Nhanvien Nhanvien { get; set; }
        public virtual Phieumuon Phieumuon { get; set; }
        public virtual Sach Sach { get; set; }
    }
}
